services:
  - type: web
    name: oecd-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app/app.py
